### ISSUE TITLE
Libspotify depreacated, Application Key not available

### ISSUE THREAD

**Issue by dmnfr** [smashingboxes/maestro#4] opened 2017-06-20 08:27 UTC
Hi,

Libspotify is deprecated since 2012, and it become complicated to get an application key from spotify.
An alternative could be to use : https://github.com/plietar/librespot , which doesn't need application keys

**Comment by dmnfr** [comment] 2017-06-20 08:37
Could also switch to https://github.com/TooTallNate/node-spotify-web

**Comment by dkniffin** [comment] 2018-03-26 14:33
Closing this as a duplicate of #3

**Closed by dkniffin** 2018-03-26 14:33 UTC
