### ISSUE TITLE
Maestro returns 404 for any slack command

### ISSUE THREAD

**Issue by eddieloeffen** [smashingboxes/maestro#7] opened 2018-05-04 10:48 UTC
I have checked out the latest version of shpotify-rewrite and got everything installed as per readme.

I have Slack connected, and slash commands are coming through my ngrok address and are being sent to Sinatra on port 4567.

Spotify is installed and opened.

It seems that whatever slack slash command I use, Sinatra / Maestro always replies with a 404.

![image](https://user-images.githubusercontent.com/2539705/39624401-3f7a51aa-4fed-11e8-934c-2dab9b04c689.png)

![image](https://user-images.githubusercontent.com/2539705/39624402-41fb1cd4-4fed-11e8-81be-d97e450fe5ed.png)

![image](https://user-images.githubusercontent.com/2539705/39624408-45538524-4fed-11e8-83ec-11bd24d88e6a.png)

**Comment by dkniffin** [comment] 2018-05-04 13:32
@eddieloeffen I think the issue is the URL you put in your slash command settings doesn't have `/maestro` at the end of it.

Also, thanks for trying this rewrite out! We'll have it merged into master soon. We've also got some ideas for future features coming down the road.

**Comment by eddieloeffen** [comment] 2018-05-04 20:48
ah, right, Thank you!

**Closed** 2018-05-04 20:49 UTC
